name: Deploy Swagger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Swagger to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./swagger
          publish_branch: gh-pages
          destination_dir: swagger
          user_name: "vaishnavi"
          user_email: "vaishnaviwarad21@gmail.com"
